env:
  browser: true
  es2021: true
extends:
  - plugin:@typescript-eslint/stylistic-type-checked
  - plugin:@typescript-eslint/recommended-type-checked
  - standard
  - prettier
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  project: true
  sourceType: module
  tsconfigRootDir: ./
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - 'dist/**/*.js'
rules:
  # '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none
        requireLast: false
      singleline:
        delimiter: comma
        requireLast: false
  lines-between-class-members: 0
  '@typescript-eslint/lines-between-class-members':
    - error
    - always
    - exceptAfterSingleLine: true
  no-dupe-class-members: 0
  '@typescript-eslint/no-dupe-class-members':
    - error
  no-redeclare: 0
  '@typescript-eslint/no-redeclare':
    - error
  no-unused-vars: 0
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: "^_"

overrides:
  - files:
    - test/**/*.ts
    - scripts/*/test/**/*.ts
    plugins:
      - jest
    extends:
      - plugin:jest/recommended
      - plugin:jest/style
