env:
  browser: true
  es2021: true
extends:
  - plugin:@typescript-eslint/recommended
  - standard
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
  - plugin:jest/recommended
  - plugin:jest/style
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  project: ./tsconfig.json
  sourceType: module
  tsconfigRootDir: ./
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none
        requireLast: false
      singleline:
        delimiter: comma
        requireLast: false
  lines-between-class-members: 0
  '@typescript-eslint/lines-between-class-members':
    - error
    - exceptAfterSingleLine: true
  no-dupe-class-members: 0
  '@typescript-eslint/no-dupe-class-members':
    - error
  no-redeclare: 0
  '@typescript-eslint/no-redeclare':
    - error
  no-unused-vars: 0
  '@typescript-eslint/no-unused-vars':
    - error
  # Conflicts with the StandardJS rule
  '@typescript-eslint/indent': off
