nodeLinker: node-modules
logFilters:
  - pattern: connected-users@workspace:scripts/connected-users doesn't provide @hotwired/stimulus *, requested by stimulus-use
    level: discard
  - pattern: connected-users@workspace:scripts/connected-users doesn't provide hotkeys-js *, requested by stimulus-use
    level: discard

yarnPath: .yarn/releases/yarn-3.4.1.cjs
