name: Build
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '32 13 * * 5'


permissions:
  contents: read

concurrency:
  # only run a single build wf per PR, cancel any existing (preceding) runs
  # for this PR.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: 'Lint'
    if: "!contains(github.event.head_commit.message, 'skip ci')
      && github.event_name != 'schedule'
      "
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            codeload.github.com:443
            github.com:443
            registry.yarnpkg.com:443
            registry.npmjs.org:443

      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Setup
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Lint
        run: yarn run lint

  testprojects:
    name: 'Determine test projects'
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')
      && github.event_name != 'schedule'
      "

    outputs:
      projects: ${{ steps.set-projects.outputs.projects }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            codeload.github.com:443
            github.com:443
            registry.yarnpkg.com:443
            registry.npmjs.org:443

      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Setup
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - id: set-projects
        name: Determine jest project names
        run: |
          PROJECTS=$(yarn run jest --showConfig | jq -c '.globalConfig.projects | map(.displayName)')
          echo "projects=${PROJECTS}" >> $GITHUB_OUTPUT

  test:
    name: Test ${{ matrix.project }}
    if: "!contains(github.event.head_commit.message, 'skip ci')
      && github.event_name != 'schedule'
      "
    needs: testprojects
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        project: ${{ fromJSON( needs.testprojects.outputs.projects ) }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            codeload.github.com:443
            github.com:443
            registry.yarnpkg.com:443
            registry.npmjs.org:443
            uploader.codecov.io:443
            codecov.io:443
            storage.googleapis.com:443

      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Setup
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Run tests
        run: yarn test --coverage --selectProjects "${{ matrix.project }}"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          directory: coverage
          flags: ${{ matrix.project }}
          token: ${{ secrets.CODECOV_TOKEN }}

  test-summary:
    name: Test matrix status
    runs-on: ubuntu-latest
    needs: [test]
    if: "always()
      && !contains(github.event.head_commit.message, 'skip ci')
      && github.event_name != 'schedule'
      "
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe  # v1.2.2
      with:
        jobs: ${{ toJSON(needs) }}

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            codeload.github.com:443
            github.com:443
            uploads.github.com:443
            objects.githubusercontent.com:443

      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@29b1f65c5e92e24fe6b6647da1eaabe529cec70f # v2.3.3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@29b1f65c5e92e24fe6b6647da1eaabe529cec70f # v2.3.3
        with:
          category: "/language:javascript"

  release:
    name: Release
    if: "!contains(github.event.head_commit.message, 'skip ci')
      && github.event_name == 'push'
      "
    needs:
      - lint
      - test-summary
      - analyze
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            codeload.github.com:443
            github.com:443
            registry.yarnpkg.com:443
            registry.npmjs.org:443
            uploads.github.com:443

      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Setup
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          HUSKY: 0
        run: yarn run release