name: Build
on:
  pull_request_target:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  # only run a single build wf per PR, cancel any existing (preceding) runs
  # for this PR.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # v1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            artifactcache.actions.githubusercontent.com:443
            codeload.github.com:443
            github.com:443
            kv4gacprodeus2file3.blob.core.windows.net:443
            registry.yarnpkg.com:443

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2

      - name: Setup
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v2
        with:
          node-version: lts/gallium
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn run lint

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      security-events: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # v1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            codeload.github.com:443
            uploads.github.com:443

      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@c3b6fce4ee2ca25bc1066aa3bf73962fda0e8898 # v1
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@c3b6fce4ee2ca25bc1066aa3bf73962fda0e8898 # v1

  build:
    needs:
      - lint
      - analyze
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # v1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            artifactcache.actions.githubusercontent.com:443
            codeload.github.com:443
            github.com:443
            kv4gacprodeus2file3.blob.core.windows.net:443
            registry.yarnpkg.com:443

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Setup
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v2
        with:
          node-version: lts/gallium
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Release
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: npm run release
