name: Build
on:
  workflow_run:
    workflows: ["Validate"]
    types:
      - completed

permissions:
  contents: read

concurrency:
  # only run a single build wf per PR, cancel any existing (preceding) runs
  # for this PR.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    if: "github.event.workflow_run.conclusion == 'success' && !contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            codeload.github.com:443
            github.com:443
            registry.yarnpkg.com:443
            registry.npmjs.org:443

      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          ref: ${{ github.workflow_run.event.head_branch }}

      - name: Setup
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Release
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          HUSKY: 0
        run: yarn run release
