name: Build
on:
  pull_request_target:
  push:
    branches:
      - main
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn run lint
