name: Dependabot auto-merge
on: pull_request_target

permissions: read-all

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813 # v1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@90ed90dba204fdf8970c1f891b4349c96353f220 # v1.1.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Approve PR
        if: >
          ${{
               steps.metadata.outputs.dependency-type == 'direct:production'
            || steps.metadata.outputs.dependency-type == 'direct:development'
            || steps.metadata.outputs.update-type == 'version-update:semver-minor'
          }}
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Enable auto-merge for Dependabot PRs
        if: >
          ${{
               steps.metadata.outputs.dependency-type == 'direct:production'
            || steps.metadata.outputs.dependency-type == 'direct:development'
            || steps.metadata.outputs.update-type == 'version-update:semver-minor'
          }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
