name: Labeller
on:
  pull_request_target:
    types:
      - auto_merge_disabled
      - auto_merge_enabled
      - opened
      - synchronize
      - reopened
  
permissions: {}

env:
  OCTOKIT_DEBUG: true
  OCTOKIT_RETRIES: 3

jobs:
  add_remove_labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443

      - name: Add auto-merge label
        # uses: actions/github-script@c1485da120d9fae32e0d884cded8ce0aa82ab1cb # v6.4.0
        uses: mjpieters/github-script@0c8fe71a7aac52b69510dff49515dbde5cc7161e # v6.5.0-pre.1
        if: github.event.action == 'auto_merge_enabled'
        with:
          debug: ${{ env.OCTOKIT_DEBUG }}
          retries: ${{ fromJSON(env.OCTOKIT_RETRIES) }}
          script: |
            core.debug(
              JSON.stringify(
                await github.rest.issues.addLabels({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ['auto-merge']
                })
              )
            )

      - name: Remove auto-merge label
        # uses: actions/github-script@c1485da120d9fae32e0d884cded8ce0aa82ab1cb # v6.4.0
        uses: mjpieters/github-script@0c8fe71a7aac52b69510dff49515dbde5cc7161e # v6.5.0-pre.1
        if: github.event.action == 'auto_merge_disabled'
        with:
          debug: ${{ env.OCTOKIT_DEBUG }}
          retries: ${{ fromJSON(env.OCTOKIT_RETRIES) }}
          script: |
            core.debug(
              JSON.stringify(
                await github.rest.issues.removeLabel({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: 'auto-merge'
                })
              )
            )

      - name: Set userscript-specific labels
        # uses: actions/github-script@c1485da120d9fae32e0d884cded8ce0aa82ab1cb # v6.4.0
        uses: mjpieters/github-script@0c8fe71a7aac52b69510dff49515dbde5cc7161e # v6.5.0-pre.1
        if: contains(fromJSON('["opened", "synchronize", "reopened"]'), github.event.action)
        with:
          debug: ${{ env.OCTOKIT_DEBUG }}
          retries: ${{ fromJSON(env.OCTOKIT_RETRIES) }}
          script: |
            const number = context.issue.number

            // Determine what userscripts are defined at the PR HEAD SHA. Each
            // userscript name is also the name of a label.
            const { data: { entries = [] } } = await github.rest.repos.getContent({
              ...context.repo, ref: context.sha, path: 'scripts',
              mediaType: { format: 'object' }
            })
            core.debug(`response entries: ${JSON.stringify(entries)}`)
            const scriptNames = entries.reduce(
              (results, e) => (e.type === 'dir' ? [...results, e.name] : results),
              []
            )
            core.info(`Known userscripts: ${scriptNames.join(', ')}`)
            if (scriptNames.length === 0) return

            // Determine the existing labels on this PR
            const { data: { labels } } = await github.rest.pulls.get({
              ...context.repo, pull_number: number
            })
            core.debug(`PR label entries: ${JSON.stringify(labels)}`)
            const existingLabels = new Set(labels.map((l) => l.name))
            core.info(`Existing PR labels: ${[...existingLabels].join(', ')}`)

            // Determine what files have been touched
            const listFilesOptions = github.rest.pulls.listFiles.endpoint.merge({
              ...context.repo, pull_number: number
            })
            const changedFiles = await github.paginate(listFilesOptions)
            const changedFileNames = changedFiles.map((f) => f.filename)
            core.debug(`Changed files: ${JSON.stringify(changedFileNames)}`)

            // if there are changes for a userscript, add the matching label
            // otherwise, if there is an existing label for a userscript the
            // PR no longer touches, remove it again.
            const missingLabels = []
            for (const scriptName of scriptNames) {
              const hasLabel = existingLabels.has(scriptName)
              const needle = `scripts/${scriptName}/`
              const touchedScript = changedFileNames.some((f) => f.startsWith(needle))
              if (touchedScript && !hasLabel) missingLabels.push(scriptName)
              else if (!touchedScript && hasLabel) {
                core.info(`Removing existing label ${scriptName} from PR`)
                await github.rest.issues.removeLabel({
                  ...context.repo, issue_number: number, name: scriptName,
                })
              }
            }
            if (missingLabels.length > 0) {
              core.info(`Adding labels to PR: ${missingLabels.join(", ")}`)
              await github.rest.issues.addLabels({
                ...context.repo, issue_number: number, labels: missingLabels,
              })
            }
